# Project identification
sonar.projectKey=collegia-cal
sonar.projectName=Collegia Cal Frontend

# Where the source code is located
sonar.sources=src

# Exclude test files from being scanned as production code
sonar.exclusions=src/**/*.test.tsx, src/**/*.test.ts, src/setupTests.ts

# Where the tests are located
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx, src/**/*.test.ts

# Language
sonar.language=ts