import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calendar, MapPin, Users, Building2, DollarSign, Clock, UserPlus } from "lucide-react";
import { format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";

interface Event {
  id: string;
  title: string;
  description?: string;
  venue: string;
  start_date: string;
  end_date: string;
  status: string;
  expected_attendees?: number;
  budget?: number;
  department?: string;
  committee_name?: string;
  created_by: string;
  registration_enabled?: boolean;
}

interface EventDetailsModalProps {
  event: Event | null;
  isOpen: boolean;
  onClose: () => void;
}

export const EventDetailsModal = ({ event, isOpen, onClose }: EventDetailsModalProps) => {
  const [isRegistering, setIsRegistering] = useState(false);
  const { user, profile } = useAuth();
  const { toast } = useToast();

  if (!event) return null;

  const formatDate = (dateString: string) => {
    return format(new Date(dateString), "MMM dd, yyyy 'at' h:mm a");
  };

  const handleRegister = async () => {
    if (!user || !profile) {
      toast({
        title: "Authentication Required",
        description: "Please log in to register for events.",
        variant: "destructive",
      });
      return;
    }

    if (profile.role !== 'student') {
      toast({
        title: "Access Denied",
        description: "Only students can register for events.",
        variant: "destructive",
      });
      return;
    }

    setIsRegistering(true);
    try {
      const { error } = await supabase
        .from('event_registrations')
        .insert({
          event_id: event.id,
          student_id: user.id,
          ticket_number: '', // This will be auto-generated by the trigger
        });

      if (error) throw error;

      toast({
        title: "Registration Successful!",
        description: "You have been registered for this event. Check your registrations tab for your ticket.",
      });
      onClose();
    } catch (error: any) {
      if (error.code === '23505') {
        toast({
          title: "Already Registered",
          description: "You are already registered for this event.",
          variant: "destructive",
        });
      } else {
        toast({
          title: "Registration Failed",
          description: "There was an error registering for this event. Please try again.",
          variant: "destructive",
        });
      }
    } finally {
      setIsRegistering(false);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'final_approved': return 'bg-success text-success-foreground';
      case 'gs_approved': return 'bg-primary text-primary-foreground';
      case 'submitted': return 'bg-warning text-warning-foreground';
      default: return 'bg-muted text-muted-foreground';
    }
  };

  const isStudent = profile?.role === 'student';
  const canRegister = isStudent && event.registration_enabled && event.status === 'final_approved';

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="text-xl font-bold">{event.title}</DialogTitle>
            <Badge className={getStatusColor(event.status)}>
              {event.status === 'final_approved' ? 'Approved' : event.status}
            </Badge>
          </div>
        </DialogHeader>

        <div className="space-y-6">
          {/* Event Description */}
          {event.description && (
            <div>
              <h4 className="font-medium mb-2">Description</h4>
              <p className="text-muted-foreground leading-relaxed">{event.description}</p>
            </div>
          )}

          {/* Event Details Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <Calendar className="h-5 w-5 text-primary mt-0.5" />
                <div>
                  <p className="font-medium">Start Date</p>
                  <p className="text-sm text-muted-foreground">{formatDate(event.start_date)}</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <Clock className="h-5 w-5 text-primary mt-0.5" />
                <div>
                  <p className="font-medium">End Date</p>
                  <p className="text-sm text-muted-foreground">{formatDate(event.end_date)}</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <MapPin className="h-5 w-5 text-primary mt-0.5" />
                <div>
                  <p className="font-medium">Venue</p>
                  <p className="text-sm text-muted-foreground">{event.venue}</p>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              {event.expected_attendees && (
                <div className="flex items-start gap-3">
                  <Users className="h-5 w-5 text-primary mt-0.5" />
                  <div>
                    <p className="font-medium">Expected Attendees</p>
                    <p className="text-sm text-muted-foreground">{event.expected_attendees}</p>
                  </div>
                </div>
              )}

              {event.department && (
                <div className="flex items-start gap-3">
                  <Building2 className="h-5 w-5 text-primary mt-0.5" />
                  <div>
                    <p className="font-medium">Department</p>
                    <p className="text-sm text-muted-foreground">{event.department}</p>
                  </div>
                </div>
              )}

              <div className="flex items-start gap-3">
                <Users className="h-5 w-5 text-primary mt-0.5" />
                <div>
                  <p className="font-medium">Organized By</p>
                  <p className="text-sm text-muted-foreground">{event.committee_name || 'Unknown Committee'}</p>
                </div>
              </div>

              {event.budget && (
                <div className="flex items-start gap-3">
                  <DollarSign className="h-5 w-5 text-primary mt-0.5" />
                  <div>
                    <p className="font-medium">Budget</p>
                    <p className="text-sm text-muted-foreground">₹{event.budget.toLocaleString()}</p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {canRegister && (
            <div className="mt-6 pt-4 border-t">
              <Button 
                onClick={handleRegister} 
                disabled={isRegistering}
                className="w-full"
              >
                <UserPlus className="mr-2 h-4 w-4" />
                {isRegistering ? "Registering..." : "Register for Event"}
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};