// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iipwchtyckcptplznyey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcHdjaHR5Y2tjcHRwbHpueWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDkzNDYsImV4cCI6MjA3MDY4NTM0Nn0.ULlGuAhHNCXMTgx7_KcTqsnY3IZrtZoeLYvt4iFb9Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});